### PR TITLE
Suggested Area and fix for #189

### LINKED ISSUE #189: Configuration instruction outdated
The configuration instruction is dated and needs to up updated, in particular the MQTT parts.

The installation is much simpler than what is described. **No configuration** is needed at all in `configuration.yaml`.
The current instruction is confusing people with fresh installs.

Installation instruction with Mosquitto broker:
- Install Mosquitto as per instruction (Supervisor ==> Add-on Store ==> Mosquitto broker ==> Install)
- Find your MQTT username and password:
-- Configuration ==> Integrations ==> Configure (Mosquitto broker) ==> RE-CONFIGURE MQTT ==> Click the "eye" to get your password

Configure ha-plejd:
mqttBroker = http://localhost
mqttUsername = homeassistant (or whatever Mosquitto broker was configured to)
mqttPassword = [whatever Mosquitto broker was configured to]

### PR DESCRIPTION
**Pull request by faanskit**
Plejd Rooms are configured in Home Assistant as Suggested Area.

Includes disputed change in `plejd/MqttClient.js`:
```
-    identifiers: `${device.deviceId}`,
+    identifiers: `${device.uniqueId}`,
```

Without it it the PR will not work properly, amongs other things as indicated in this [comment](https://github.com/icanos/hassio-plejd/pull/179#issuecomment-834286512).

Improved documentation inc. suggested updated instruction for Mosquitto to resolve #189

### CODE REVIEW

**Comment by faanskit** [comment]
> room hinting is still a good idea 

Yes, it works remarkably well. The typical electrician will name things to what they are (e.g. Spotlights) and use rooms to differentiate them. He will not call them "Spotlights in hallway" and place them in the "Hallway" room in Plejd.

A freshly installed system (HA) will replicate exactly what the electrician left in Plejd with this PR. So this PR will increase usability.

The Google Assistant integration with Plejd work well with this scheme as well. E.g. "Hey Google, turn off lights in the kitchen" works just fine; or "Hey Google, turn on the spotlights in the kitchen"

I also understand that a HomeKit integration works well with this as well. Have not tested myself though.

File: plejd/PlejdApi.js [hunk 1]
```diff
@@ -436,6 +436,8 @@ class PlejdApi {
             loadType = 'light';
           }
 
+          const room = this.siteDetails.rooms.find((x) => x.roomId === device.roomId);
```
Comment (SweVictor) [inline plejd/PlejdApi.js:439]: `room.x` (below) will crash if room is not found. Recommend appending a default value
`= this.siteDetails.....  || {}` 

Alt is to always set similar to `room: room ? room.title : undefined`

File: plejd/README.md [hunk 2]
```diff
@@ -1,9 +1,32 @@
 # Hass.io Plejd add-on
 
 Hass.io add-on for Plejd home automation devices. Gives you the ability to control the Plejd home automation devices through Home Assistant.
-It uses MQTT to communicate with Home Assistant and supports auto discovery of the devices in range.
-
-It also supports notifications so that changed made in the Plejd app are propagated to Home Assistant.
+It uses MQTT to communicate with Home Assistant and supports auto discovery of the devices in range. Changed made in the Plejd app are propagated to Home Assistant.
+
+Plejd output devices typically appears as either lights or switches in Home Assistant depending on how they are configured.
+<table>
```
Comment (SweVictor) [inline plejd/README.md:7]: I find this a bit unreadable. Can we use the | | markdown syntax?

```
| Device | Plejd Configuration | Home Assistant Role | Comment                                                               |
|--------|---------------------|---------------------|-----------------------------------------------------------------------|
| CTR-01 | Relay, Light        | Light               |                                                                       |
| CTR-01 | Relay, Other        | Switch              |                                                                       |
| REL-01 | Relay, Light        | Light               |                                                                       |
| REL-01 | Relay, Other        | Switch              |                                                                       |
| REL-02 | Relay, Light        | Light               |                                                                       |
| REL-02 | Relay, Other        | Switch              |                                                                       |
| SPR-01 | Relay, Light        | Light               | Not tested, not released by Plejd                                     |
| SPR-01 | Relay, Other        | Switch              | Not tested, not released by Plejd                                     |
| DIM-01 | -                   | Light               |                                                                       |
| DIM-02 | -                   | Light               |                                                                       |
| LED-10 | -                   | Light               |                                                                       |
| DAL-01 | -                   | -                   | Not supported, not released by Plejd                                  |
| WPH-01 | -                   | Device Automation   | type:button_short_press, subtype:button_1, button_2,button_3,button_4 |
| WRT-01 | -                   | Device Automation   | type:button_short_press, subtype:button_1                             |
| GWY-01 | -                   | -                   |                                                                       |
| RTR-01 | -                   | -                   |                                                                       |
| Scene  | -                   | Scene               |                                                                       |
| Scene  | -                   | Device Automation   | type:scene, subtype:trigger                                           |
| Room   | -                   | Area                | Can be changed by Home Assistant                                      |
| Room   | -                   | Light               | If includeRoomsAsLights is set to true                                |
```

File: plejd/README.md [hunk 3]
```diff
@@ -108,7 +132,16 @@ If you restore a backup from a 32bit system to a new 64bit system, use the Rebui
 
 ### Configuration
 
-You need to add the MQTT integration to Home Assistant either by going to Configuration -> Integrations and clicking the Add Integration button, or by adding the following to your `configuration.yaml` file:
+#### Simple MQTT Configurations
+When you are using the official Mosquitto Broker from Home Assistant Add-on store, minimal configuration is required.
+<table>
```
Comment (SweVictor) [inline plejd/README.md:137]: Same here

File: plejd/README.md (hunk 2 above)
Comment (SweVictor) [reply plejd/README.md:7]: Another thing - maybe "not released" is a bad phrasing since it might not be true for the duration of the release. Maybe just mark them as "not tested, might work" / "not supported" or similar?

File: plejd/types/DeviceRegistry.d.ts [hunk 4]
```diff
@@ -13,6 +13,7 @@ export interface OutputDevice {
   name: string;
   output: number;
   roomId: string;
+  roomName: string;
```
Comment (SweVictor) [inline plejd/types/DeviceRegistry.d.ts:16]: maybe both this and `roomId` should really be `string | undefined` since we don't require it always?

**Review by SweVictor — APPROVED** [review]
Some minor suggestions

**Comment by SweVictor** [comment]
Resolves #193

File: plejd/PlejdApi.js (hunk 1 above)
Comment (faanskit) [reply plejd/PlejdApi.js:439]: Point taken, but competency is lacking on my side.
Trial, error and googling did not help.
Can you provide some more details how to exactly do this. Sorry for asking.

The rest of the comments I should be proficient to handle :-)

Comment (faanskit) [reply plejd/PlejdApi.js:439]: Got it, finally.

**Comment by faanskit** [comment]
Take note: Also when rooms are registered as devices they will belong to a room (=itself).
I was not sure if that was the desired behavior; it just "felt" right. And; what sparked the discussion in #191

**Comment by SweVictor** [comment]
> Take note: Also when rooms are registered as devices they will belong to a room (=itself).

Good note. Not sure which is better. Just turning on or off a HA room will send double commands but still work well. Transitioning a HA room or lights.all will behave very strangely when using room lights (blinking often). 

Since scenes have been moved to the right domain they're not s problem anymore. So rooms - no room, their own room or a virtual room "Rooms"? 

Also thinking about naming. I typically get quite confused since I get multiple UI switches all called "Room name". Prefix with "Plejd"? "Plejd Living room"?

I probably vote for no room and use prefix, but have no super strong opinion. Choose a way and write when you feel ready to merge @faanskit

**Comment by faanskit** [comment]
> I probably vote for no room and use prefix, but have no super strong opinion.

I second the "no room" based on the viewpoint you gave. But, see proposal below.

> Also thinking about naming. I typically get quite confused since I get multiple UI switches all called "Room name". Prefix with "Plejd"? "Plejd Living room"?

Just to be sure: You refer to the name of the "Room Switch" get in Home Assistant?
The only _con_ for adding prefix is change of behavior/naming for current users.

How about this:

1. Plejd Room Switches keep their name (no prefix)
2. Plejd Room Switches are allocated to a suggested_room called "Plejd Room Switches"

The above proposal will reduce the confusion you refer to and solve the problem of having switches and lights twice in the same HA room.

Agree?

**Comment by SweVictor** [comment]
> > I probably vote for no room and use prefix, but have no super strong opinion.
> 
> I second the "no room" based on the viewpoint you gave. But, see proposal below.

Maybe this is a non-issue after all. `lights.all` will work the same either way, the HA UI does not support transitions. So maybe setting room as you do now is fine.

> > Also thinking about naming. I typically get quite confused since I get multiple UI switches all called "Room name". Prefix with "Plejd"? "Plejd Living room"?
> 
> Just to be sure: You refer to the name of the "Room Switch" get in Home Assistant?
> The only _con_ for adding prefix is change of behavior/naming for current users.
> 
> How about this:
> 
> 1. Plejd Room Switches keep their name (no prefix)
> 2. Plejd Room Switches are allocated to a suggested_room called "Plejd Room Switches"

I really don't know 😄 

The problem with [text] is that we don't support translations. So for a Swedish user you would get "Vardagsrum"/"Kök"/"Plejd Room Switches" with the suggested solution, a bit strange. 

So... After thinking a bit more I probably suggest either keeping as-is (user can rename room switches if they want) or possibly add the "Plejd" prefix. IF we are to add a prefix, now is the time since we will break a lot in v0.8.0

**Comment by faanskit** [comment]
> So... After thinking a bit more I probably suggest either keeping as-is (user can rename room switches if they want) or possibly add the "Plejd" prefix. IF we are to add a prefix, now is the time since we will break a lot in v0.8.0

I'll do this:
Plejd Room Switch will not use suggested_room.

I'll push a change later today.

**Comment by SweVictor** [comment]
Alright. Or keep it as-is 😄 

When using the UI (which is probably the only time rooms auto-group anything) it won't matter (you will send double commands over BLE, but user won't notice)

**Comment by faanskit** [comment]
Ready for merge.

File: plejd/PlejdApi.js [hunk 5]
```diff
@@ -523,7 +523,7 @@ class PlejdApi {
           name: room.title,
           output: undefined,
           roomId,
```
Comment (SweVictor) [inline plejd/PlejdApi.js:525]: set this to undefined as well

**Review by SweVictor — CHANGES_REQUESTED** [review]

**Review by SweVictor — APPROVED** [review]
